choice/config/routes.rb
Choice::Application.routes.draw do
  get '/choices/new', controller: 'choices', action: 'new', as: 'new_choice'
  post '/choices', controller: 'choices', action: 'create'

  get '/choices', controller: 'choices', action: 'index', as: 'choices'
  get '/choices/:id', controller: 'choices', action: 'show', as: 'choice'

  get '/choices/:id/edit', controller: 'choices', action: 'edit', as: 'edit_choice'
  put '/choices/:id', controller: 'choices', action: 'update'

  delete '/choices/:id', controller: 'choices', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create'

  get '/categories', controller: 'categories', action: 'index', as: 'categories'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  put '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

  get '/brands/new', controller: 'brands', action: 'new', as: 'new_brand'
  post '/brands', controller: 'brands', action: 'create'

  get '/brands', controller: 'brands', action: 'index', as: 'brands'
  get '/brands/:id', controller: 'brands', action: 'show', as: 'brand'

  get '/brands/:id/edit', controller: 'brands', action: 'edit', as: 'edit_brand'
  put '/brands/:id', controller: 'brands', action: 'update'

  delete '/brands/:id', controller: 'brands', action: 'destroy'

end

choice/app/models/brand.rb
class Brand < ActiveRecord::Base
end

choice/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :Brands
end

choice/app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :User
  belongs_to :Category
  belongs_to :Brand
end

choice/app/models/user.rb
class User < ActiveRecord::Base
end

choice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

choice/app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find_by_id(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new
    @brand.name = params[:name]

    if @brand.save
      redirect_to brands_url
    else
      render 'new'
    end
  end

  def edit
    @brand = Brand.find_by_id(params[:id])
  end

  def update
    @brand = Brand.find_by_id(params[:id])
    @brand.name = params[:name]

    if @brand.save
      redirect_to brands_url
    else
      render 'new'
    end
  end

  def destroy
    @brand = Brand.find_by_id(params[:id])
    @brand.destroy
    redirect_to brands_url
  end
end

choice/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new
    @category.name = params[:name]
    
    if @category.save
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
  end

  def update
    @category = Category.find_by_id(params[:id])
    @category.name = params[:name]
    
    if @category.save
      redirect_to categories_url
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find_by_id(params[:id])
    @category.destroy
    redirect_to categories_url
  end
end

choice/app/controllers/choices_controller.rb
class ChoicesController < ApplicationController

  def index
    @choices = Choice.all
  end

  def show
    @choice = Choice.find_by_id(params[:id])
  end

  def new
    @choice = Choice.new
  end

  def create
    @choice = Choice.new
    
    if @choice.save
      redirect_to choices_url
    else
      render 'new'
    end
  end

  def edit
    @choice = Choice.find_by_id(params[:id])
  end

  def update
    @choice = Choice.find_by_id(params[:id])
    
    if @choice.save
      redirect_to choices_url
    else
      render 'new'
    end
  end

  def destroy
    @choice = Choice.find_by_id(params[:id])
    @choice.destroy
    redirect_to choices_url
  end
end

choice/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:email]
    @user.password_digest = params[:password_digest]
    @user.gender = params[:gender]
    @user.age = params[:age]
    
    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.email = params[:email]
    @user.password_digest = params[:password_digest]
    @user.gender = params[:gender]
    @user.age = params[:age]
    
    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

choice/app/helpers/application_helper.rb
module ApplicationHelper
end

choice/app/views/brands/edit.html.erb
<h1>Editing Brand #<%= @brand.id %></h1>


<%= form_tag(brand_url(@brand), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @brand.name %>
  </div>

  
  <div>
    <%= submit_tag "Update Brand" %>
  </div>

<% end %>

choice/app/views/brands/index.html.erb
<h1>Brands</h1>

<p><%= link_to 'Add a New Brand', new_brand_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @brands.each do |brand| %>
    <tr>
      <td><%= brand.name %></td>
  
      <td><%= link_to 'Show', brand_url(brand) %></td>
      <td><%= link_to 'Edit', edit_brand_url(brand) %></td>
      <td><%= link_to 'Destroy', brand_url(brand), method: 'delete', data: { confirm: "Do you really want to delete this brand?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

choice/app/views/brands/new.html.erb
<h1>New Brand</h1>


<%= form_tag(brands_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>


  <div>
    <%= submit_tag "Create Brand" %>
  </div>
<% end %>

choice/app/views/brands/show.html.erb
<h1>Brand #<%= @brand.id %></h1>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>

choice/app/views/categories/edit.html.erb
<h1>Editing Category #<%= @category.id %></h1>


<%= form_tag(category_url(@category), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @category.name %>
  </div>

  
  <div>
    <%= submit_tag "Update Category" %>
  </div>

<% end %>

choice/app/views/categories/index.html.erb
<h1>Categories</h1>

<p><%= link_to 'Add a New Category', new_category_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
  
      <td><%= link_to 'Show', category_url(category) %></td>
      <td><%= link_to 'Edit', edit_category_url(category) %></td>
      <td><%= link_to 'Destroy', category_url(category), method: 'delete', data: { confirm: "Do you really want to delete this category?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

choice/app/views/categories/new.html.erb
<h1>New Category</h1>


<%= form_tag(categories_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>


  <div>
    <%= submit_tag "Create Category" %>
  </div>
<% end %>

choice/app/views/categories/show.html.erb
<h1>Category #<%= @category.id %></h1>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

choice/app/views/choices/edit.html.erb
<h1>Editing Choice #<%= @choice.id %></h1>


<%= form_tag(choice_url(@choice), method: 'put') do %>

  
  <div>
    <%= submit_tag "Update Choice" %>
  </div>

<% end %>

choice/app/views/choices/index.html.erb
<h1>Choices</h1>

<p><%= link_to 'Add a New Choice', new_choice_url %></p>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @choices.each do |choice| %>
    <tr>
  
      <td><%= link_to 'Show', choice_url(choice) %></td>
      <td><%= link_to 'Edit', edit_choice_url(choice) %></td>
      <td><%= link_to 'Destroy', choice_url(choice), method: 'delete', data: { confirm: "Do you really want to delete this choice?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

choice/app/views/choices/new.html.erb
<h1>New Choice</h1>


<%= form_tag(choices_url, method: 'post') do %>



  <div>
    <%= submit_tag "Create Choice" %>
  </div>
<% end %>

choice/app/views/choices/show.html.erb
<h1>Choice #<%= @choice.id %></h1>

choice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Choice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

choice/app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :password_digest %><br />
    <%= text_field_tag :password_digest, @user.password_digest %>
  </div>

  <div>
    <%= label_tag :gender %><br />
    <%= text_field_tag :gender, @user.gender %>
  </div>

  <div>
    <%= label_tag :age %><br />
    <%= text_field_tag :age, @user.age %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

choice/app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password digest</th>
      <th>Gender</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.password_digest %></td>
      <td><%= user.gender %></td>
      <td><%= user.age %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

choice/app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :password_digest %><br />
    <%= text_field_tag :password_digest %>
  </div>

  <div>
    <%= label_tag :gender %><br />
    <%= text_field_tag :gender %>
  </div>

  <div>
    <%= label_tag :age %><br />
    <%= text_field_tag :age %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

choice/app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Gender:</b>
  <%= @user.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>